#+TITLE: 毛诗正义
#+OPTIONS: toc:nil num:nil title:nil
#+STARTUP: showall
#+TAGS: 摘抄(d) 古籍(o) 儒学(r)

* 毛诗正义

-----

2016-07-05 17:44:44

國是風化之界，詩以當國為別，故謂之《國風》。其《雅》則天子之事，政教刑于四海，不須言國也。

-----

2016-07-05 17:46:01

蓋跡其先封善否，參其詩之美惡，驗其時政得失，詳其國之大小，斟酌所宜，以為其次。

-----

2016-07-06 10:02:53

此篇言後妃性行和諧，貞專化下，寤寐求賢，供奉職事，是後妃之德也。

-----

2016-07-06 10:09:36

不言美後妃者，此詩之作，直是感其德澤，歌其性行，欲以發揚聖化，示語未知，非是褒賞後妃能為此行也。

-----

2016-07-06 10:37:47

風訓諷也，教也。諷謂微加曉告，教謂殷勤誨示。

-----

2016-07-06 10:39:20

蘊藏在心，謂之為志；發見於言，乃名為詩。

-----

2016-07-06 10:41:24

包管萬慮，其名曰心；感物而動，乃呼為志。志之所適，外物感焉，言悅豫之志則和樂興而頌聲作，憂愁之志則哀傷起而怨刺生。

-----

2016-07-06 10:46:49

在心為志，出口為言，誦言為詩，詠聲為歌，播於八音謂之為樂，皆始末之異名耳。

-----

2016-07-06 16:29:52

商之為言章也，物成熟可章度也。角，觸也。物觸地而出，戴芒角也。宮，中也。居中央，暢四方，唱始施生，為四聲之綱也。徵，祉也，物盛大而蕃祉也。羽，宇也，物聚藏宇覆之也。

注

此释直以五音配四方四时而论义。

-----

2016-07-07 10:19:54

人心感於物而後動，先王慎所以感之者，故作樂以和其聲。樂之感人深，其移風易俗

-----

2016-07-07 10:20:03

志微、噍殺之音作而民思憂，廉直、莊誠之音作而民肅敬，寬裕、順成之音作而民慈愛，流僻、邪散之音作而民淫亂。

-----

2016-07-07 10:21:23

禮者，稱人之情而為之節文，賢者俯而就之，不肖者企而及之，是下民之所行，非聖人之所行也。

-----

2016-07-07 10:22:19

夫物之感人無窮，而人之好惡無節，則是物至而人化物也。人化物也者，則滅天理而窮人欲者也。於是有悖逆詐偽之心，有淫佚作亂之事。故先王制禮作樂為之節。

-----

2016-07-07 15:32:09

上以風化下，下以風刺上

-----

2016-07-07 16:01:53

奸聲感人而逆氣應之，逆氣成象而淫樂興焉。正聲感人而順氣應之，順氣成象而和樂興焉。

-----

2016-07-07 16:06:44

民有剛柔緩急，音聲不同，系水土之風氣，故謂之風。好惡、取捨、動靜，隨君上之情欲，故謂之俗。

注

风俗之义

-----

2016-07-07 16:14:41

詩是樂之心，樂為詩之聲，故詩、樂同其功也。然則詩、樂相將，無詩則無樂。

-----

2016-07-07 16:18:17

風，言賢聖治道之遺化。賦之言鋪，直鋪陳今之政教善惡。比，見今之失，不敢斥言，取比類以言之。興，見今之美，嫌於媚諛，取善事以喻勸之。雅，正也，言今之正者，以為後世法。頌之言誦也，容也，誦今之德，廣以美之。

-----

2016-07-07 16:22:25

比之與興，雖同是附讬外物，比顯而興隱。

-----

2016-07-07 17:14:50

風、雅、頌同為政稱，而事有積漸，教化之道，必先諷動之，物情既悟，然後教化，使之齊正。言其風動之初，則名之曰風。指其齊正之後，則名之曰雅。風俗既齊，然後德能容物，故功成乃謂之頌。

-----

2016-07-07 17:17:53

風、雅、頌者，詩篇之異體；賦、比、興者，詩文之異辭耳

-----

2016-07-07 21:19:13

王者政教有小大，詩人述之亦有小大，故有小雅焉，有大雅焉。小雅所陳，有飲食賓客，賞勞群臣，燕賜以懷諸侯，征伐以強中國，樂得賢者，養育人材，於天子之政，皆小事也。大雅所陳，受命作周，代殷繼伐，荷先王之福祿，尊祖考以配天，醉酒飽德，能官用士，澤被昆蟲，仁及草木，於天子之政，皆大事也。詩人歌其大事，制為大體；述其小事，制為小體。體有大小，故分為二焉。

-----

2016-07-07 21:28:37

“四始”者，鄭答張逸雲：“風也，小雅也，大雅也，頌也。人君行之則為興，廢之則為衰。”

-----

2016-07-07 21:32:18

《詩緯·汎曆樞》雲：“《大明》在亥，水始也。《四牡》在寅，木始也。《嘉魚》在已，火始也。《鴻雁》在申，金始也。”與此不同者，緯文因金木水火有四始之義，以《詩》文讬之。

-----

2016-07-07 21:31:54

鄭作《六藝論》，引《春秋緯·演孔圖》雲：“《詩》含五際、六情”者，鄭以《汎曆樞》雲午亥之際為革命，卯酉之際為改正。辰在天門，出入候聽。卯，《天保》也。酉，《祈父》也。午，《采芑》也。亥，《大明》也。然則亥為革命，一際也；亥又為天門出入候聽，二際也；卯為陰陽交際，三際也；午為陽謝陰興，四際也；酉為陰盛陽微，五際也。

-----

2016-07-07 21:37:03

但文王所行，兼行先王之道，感文王之化為《周南》，感先王之化為《召南》，不言先王之教，無以知其然，故特著之也。

-----

2016-07-07 21:36:47

文王以諸侯而有王者之化，述其本宜為風。

-----

2016-07-07 21:38:25

文王末年，身實稱王，又不可以《國風》之詩系之王身。名無所系，詩不可棄，因二公為王行化，是故系之二公。

-----

2016-07-07 21:42:03

是以《關雎》之篇，說後妃心之所樂，樂得此賢善之女，以配己之君子；心之所憂，憂在進舉賢女，不自淫恣其色；又哀傷處窈窕幽閒之女未得升進，思得賢才之人與之共事。

-----

2016-07-08 07:48:24

此雎鳩之鳥，雖雌雄情至，猶能自別，退在河中之洲，不乘匹而相隨也，以興情至，性行和諧者，是後妃也。

-----

2016-07-08 09:02:43

《禮記·祭統》曰：“水草之菹，陸產之醢，小物備矣。三牲之俎，八簋之實，美物備矣。昆蟲之異，草木之實，陰陽之物備矣。凡天之所生，地之所長，苟可薦者，莫不鹹在，示盡物也。”是祭必備庶物也。

-----

2016-07-09 09:56:22

之、兮、矣、也之類，本取以為辭，雖在句中，不以為義，故處末者，皆字上為韻。

-----

2016-07-09 09:58:08

然人志各異，作詩不同，必須聲韻諧和，曲應金石，亦有即將助句之字，以當聲韻之體者

-----

2016-07-11 11:07:16

此言萋萋，取未成之時，喻女之少壯，故雲茂盛貌。下章指採用之時，故以“莫莫”為成就貌也。

-----

2016-07-11 11:10:53

欲明總上於飛至集，終始恒鳴，以喻後妃在家與出嫁，常有聲稱達於遠方也。

-----

2016-07-11 11:14:24

服，整也。女在父母之家，未知將所適，故習之以絺綌煩辱之事，乃能整治之無厭倦，是其性貞專。

-----

2016-07-11 11:18:32

言後妃整治此葛以為絺綌之時，志無厭倦，是後妃之性貞專也。

-----

2016-07-11 11:26:54

傳引此者，以王后、庶人之妻皆有所作，後妃在父母之家，未知將所適，雖葛之煩辱亦治之也。

-----

2016-07-11 12:24:51

我告師氏者，我見教告于女師也，教告我以適人之道。重言我者，尊重師教也。

-----

2016-07-11 19:14:23

姆，婦人五十無子，出而不復嫁，能以婦道教人者，若今時乳母矣。

-----

2016-07-11 23:39:27

褘衣，從王祭先王。褕翟，祭先公。闕翟，祭群小祀。鞠衣以告桑。展衣，以禮見王及賓客。褖衣，以禦于王。

-----

2016-07-11 23:44:07

婦人有歸宗，謂自其家之為宗者。大夫稱家，言大夫如此耳。夫人王后則不然也。天子諸侯位高，恐其專恣淫亂，故父母既沒，禁其歸寧。大夫以下，位卑畏威，故許之耳。

