#+HUGO_BASE_DIR: ~/blog
#+HUGO_SECTION: notes
#+TITLE:杂论
#+DATE:<2020-06-06 Sat>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS:古籍 儒学 笔记
#+HUGO_CATEGORIES:笔记
#+HUGO_DRAFT: false
* 天人感应

天人感应之说由来已久 尚书洪范所述箕子言即开有周一代之统治思想，儒学承之，仲舒修缮之，此是自商以来之神道设教。

* 儒法道之变通

孟子者，应法家之难而作也，中庸者，对道家之责而生也。盖法家以人性为论说之基，其说有理有实，而彼时之儒家，有其仁义之论而无其基，故子孟子立性善之说而应之。儒法者，皆外以禁內者也，儒者克己，法者绳人。克己者失于伪，绳人者失于正。故中庸之论者，以诚补伪也，韩非之论者，以道正法也。儒者立诚而法者邀道，此彼时学术之大概也。

* 三教之圣

儒道皆以崇圣为宗，圣之所为异也，然造圣则一也。佛之在华初兴亦以圣人始，孝明感梦者，感西方之圣人也，由慕西方之圣而后受西方之教，此亦佛教东传之一大因缘也。

* 读南渡北归

读毕《南渡北归》，皇皇大作，知近代学人之来龙去脉，有可仰之者，有可鄙之者，有大令人唏嘘者。心向学术者，或病于孤，或病于傲，或病于怯，或病于杂。孤傲者，无友也，孤者自伤，傲者伤人；怯杂者，无恒也，怯于克难，杂则无专，皆失于一而难成。吾孤而杂者，于人事又不甚了了，若非如此，或可遇良师欤？亦不可或知也。此书大鼓舞心向学术者之志气也，其间自有正气在，学者读之甚有益。

* 易象、诗象、字象同源

易卦有本象，有引申象，本象者，取诸卦之本义也，天地水火雷风山泽是也，引申象者，所谓近取诸身，远取诸物是也。由乾之天象取乾之健义，由健义取龙象马象，此为引申象之一例，然不止于此也，乾卦之外，余卦亦如此。然引申象之取有其定则，可依诸卦之取象寻而求之，若能求得其定则，则易之奥府可窥而见之也。易象之本义，谓森罗万象，杂而不乱，循而则之，究达天人也然古之操易者甚秘，非史巫绝无可能窥其堂奥，况史巫尚有愚钝者，窥而不见者也，故后世罕得其传，取而代之者，以五行杂配为基之术数也。此术数之源流及利弊尚需探讨，于此暂且不表。
诗之兴者亦有本义引申义，意象之联想勾引定一诗叙事之基调。易林往往引诗以为断文，盖因诗易之相通也。由一卦之总意象定卦事之吉凶，旁通钩引诸旁象以定情实，故易林辞虽杂而有本，然何为主象，何为旁象，由何爻定吉凶尚需考量。
尔雅所录之字义亦多有可思之处，是否可搜集最小字义集合之汉字，由此集合引申变换出其他汉字？

