#+HUGO_BASE_DIR: ~/blog
#+HUGO_SECTION: digest
#+DATE:<2020-06-06 Sat>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS:摘抄 文学 西方 现代
#+HUGO_CATEGORIES:摘抄
#+HUGO_DRAFT: false
#+TITLE: 佩索阿
#+OPTIONS: title:nil toc:nil num:nil \n:t

* 佩索阿诗选/恐惧之夜
在恐惧之夜，
所有夜晚的自然本质，
在失眠之夜，
所有我的夜晚的自然本质，
我记得，
在摇摇晃晃的磕睡中醒来，
我记得，
我做过的以及在生命中我也许已经该做过的一切。
我记得，而一种怒火
传遍我的全身，
就像身体的一阵寒冷或一种恐惧，
我的无法挽回的过去---这才是真正的死尸。
所有其他的死尸很可能只是错觉。
所有的死者也许还在另外的地方活着。
所有我过去的时光也许还在什么地方，
在幻觉的时空之中，存在着。
在消失的谎言中。

但从前我所不是的那个东西，
我没做过的事情，
我没有梦见过的东西；
什么是现在我才看清我该已经完成的，
什么是现在我才清楚地看见我该已经---这是那个超过所有上帝的已死的东西，
这个---总之，它曾是我生命中最好的部分---它甚至
不是上帝所赋予生命的……

如果在某个确定的地点我转向左边而非右边；
如果在某个确定的时刻，
我说了是而非否，或说了否而非是；
如果在某次交谈中
我忽然想出一个句子，而现在我在昏睡中却要仔细推敲---
如果事情是这样，今天我就会截然不同，也许整个宇宙
会在昏迷不醒中被复活成另一个样子。

但在那不可挽回地失去的方向上，我不曾改变，
一点没变，想都没想过，只是现在我才认清了它；
但我并未说YES或NO，只是现在才注意我没说过这个；
但我未能完成的诗句如今却在我心中翻涌不息，它们全都
清澈，自然，逼真，
最后，谈话集中了，
全部的问题都解决了……
但只是现在，那从未存在的，也的确不会存在的事物，伤害着。

我确实已错过的，在任何的形而上学体系中，
都没有抓住一点希望。
也许我能将我梦见过的带到另外的世界。
但我怎能将我忘记梦见的事物带给另外的世界？
是的，这些将要去乞求的梦，是真正的死尸。
我把它永远埋葬在我心中，为了全部的时间，
为了全部的宇宙。

今夜，我无法入睡，而宁静环绕我
像一种我无缘分享的真理，
而月光在户外，像我无法拥有的希望，
对我来说是看不见的。
-----
* 佩索阿诗选/我是逃跑的那个
我是逃跑的那个，
我出生后
他们把我锁在我里面
可我跑了。
我的灵魂寻找我，
穿过山岗与山谷，
我希望我的灵魂
永远找不到我。
-----
* 佩索阿诗选/我知道，我孤独
我知道，我孤独
它伤得多深呵，这颗心
没有信念，没有律法
没有悦耳的音调，也没有思想。
只有我，只有我
而我对此又说不出什么
因为感觉像天空——
被看见，它里面又无物可看。
-----
* 佩索阿诗选/牧羊人
牧羊人
事物的神秘？我该怎样了解神秘是什么？
唯一的神秘是那儿有个人他也许思考着神秘。
一个站在阳光中的人，闭上眼睛
开始忘记太阳是什么
去想许多炙热的东西。
但他张开眼睛，看见太阳，
现在他再也不能想着任何东西，
因为阳光远远胜过
所有哲人所有诗人的思想。
阳光不知道它正在做什么
所以它不会堕入迷途，所以它平常，它不赖。
-----
* 惶然录/我这张脸是谁
我瘦削的，呆板的面孔，没有表现出智慧，没有表露情感的强度，没有任何东西可以使这张脸从其他面孔组成的凝固的浪潮里脱颖而出。然而，其他那些脸不是凝固的浪潮，其中确有一些表情丰富的面容。
-----
* 惶然录/下坠
踏着我梦想和疲惫的脚步，从你的虚幻中下坠，下坠，而且成为我在这个世界中的替身。
旅行者本身就是旅行。
如果我想象什么，我就能看见它。如果我旅行的话，我会看得到更多的什么吗？只有想象的极端贫弱，才能为意在感受的旅行提供辩解。
事实上，世界的终点以及世界的起点，只不过是我们有关世界的概念。仅仅是在我们的内心并不是里，景观才成为景观。这就是为什么说我想象他们，我就是在创造他们。如果我创造它们，它们就存在。如果它们存在，那么我看见它们就像我看见别的景观。所以干嘛要旅行呢？
 我们看到的，并不是我们所看到的，而是我们自己。
-----
* 惶然录/单调产生的快乐
文学想象的核心错误，就是这样的观念：别人都像我们并且必定像我们一样感受。人类的幸运在于，每一个人都是他们自己，只有天才才被赋予成为别人的能力。
真正的聪明人，能够从他自己的躺椅里欣赏整个世界的壮景，无需同任何人说话，无须了解任何阅读的方法，他仅仅需要知道如何运用自己的五种感官，还有一颗灵魂里纯真的悲哀。
一个人为了摆脱他的单调，必须使存在单调化。一个人必须使每一天都如此平常不觉，那么在最微小的事故中才有欢娱可供探测。
因为我是无，我才能够想象我自己是一切。如果我是某个人，我就不能够进入想象中的这个人。……他的现实限制他的感觉。
-----
* 惶然录/既不崇高也不低贱
是的，我生活在无比肮脏而且平常的真实生活中，也生活在无比激烈而且持久的梦幻化生活中。我像一个放风时醉酒的奴隶，两种痛苦同居于一具躯体。
-----
* 惶然录/艺术在另一间房里
是的，艺术，与生活在同一条街上，给生活减压的艺术实际上并没有给生活减除任何东西，它同生活自身一样单调，只是表现为另一种不同的形式。
-----
* 惶然录/被上帝剥削
一些先知和圣徒行走于空空人世，他们被他们的上帝剥削。
-----
* 惶然录/个性与灵魂
给每一种情绪赋予个性，给每一种思维状态赋予灵魂。
-----
* 惶然录/我是无
我是某座不曾存在的城市的荒郊，某本不曾动笔的著作的冗长序言。我是无，是无。我不知道如何去感受，或者思考，或者爱。我是一本还没有开始写作的长篇小说里的人物，我 在我还未存在之前翱翔长空，然后被取消；在我还未存在之前一次次 梦想；梦想着一个人，而那一个人从来就没有打算赋予我生命。
我总是思考，总是感受，但我的思想全无缘故，感觉全无根由。我正在一脚踩空，毫无方向地空空跌落，通过无限之域而落入无限。我的灵魂是一个黑色的大漩涡，一团正在旋搅出真空状态的大疯狂，巨大的水流旋出中心的空洞，而水流，比水流更加回旋湍急的，是我在人世间所见所闻的一切意向汹涌而来：房子，面孔，书本，垃圾箱，音乐片段以及声音碎片，所有这一切被拽入一个不祥的无底洞。
只因为任何一个圆环都得有一个中心，我这个中心因此才得以存在。我，我自己，是井壁坍塌残浆仅存的一口井，我是被巨大空无所包围的一切的中心。 
