#+HUGO_BASE_DIR: ~/blog
#+HUGO_SECTION: digest
#+DATE:<2020-06-06 Sat>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS:摘抄 古籍 儒学 易学
#+HUGO_CATEGORIES:摘抄
#+HUGO_DRAFT: false
#+TITLE: 焦氏易诂
#+OPTIONS: toc:nil num:nil title:nil
#+STARTUP: showall
#+TAGS: 摘抄(d) 古籍(o) 儒学(r) 易学(y)

* 焦氏易诂

-----

2017-07-17 12:33:37

《渐之屯》云：“东山西山。”屯中爻艮山，震后天在东，故曰“东山”；上坎，坎西，故曰“西山”。

注：

先天後天混用？

-----

2017-07-24 00:28:12

盖对象者，阳与阴相对，阴与阳相对。阴阳既相对，即常往来流通，合而为一，不能分析。覆象者，艮反为震，震反为艮，兑反为巽，巽反为兑，正倒虽不同而体则一。半象者，杭辛斋云：基于卦位。震初位，艮三位；震起艮止，中自然离，故离兼艮震，离位二也。巽位在四，兑位在上；兑见巽伏，中自然坎，故坎兼兑巽，坎位五也。

-----

2017-07-28 00:06:14

然则阴阳二气，实不能分不能离，见阴即知阳。见阳即知阴。《易·彖》已如此。此由《易林》视本象与对象相通而推得之也。

-----

2017-07-28 00:08:36

茲《易林·剥之复》云：“班马还师。”复下震，震为马，上坤、互坤亦为马，故曰“班马”。又《观之既济》、《夬之否》皆有此词，皆以多马班列取象。

-----

2017-07-28 00:09:02

诚以屯下震、中爻坤、上坎皆有马象，马多而前后班列，故曰“班如”也。

-----

2017-07-28 00:10:19

屯之即鹿，实麋鹿之鹿，取象震也。

-----

2017-07-28 00:14:03

然则无虞者，言勿以鹿为微物而轻忽之，致空入林中而无所获也。

-----

2017-07-28 12:34:09

自焦氏以坤为水，为江河，此象确定后，凡《易》言利涉大川者，皆迎刃而解。

-----

2017-07-28 12:42:05

茲以坤为大川，需上坎，言阳往居坤中，得位，故利涉。

-----

2017-07-28 12:43:03

自《左氏》谓谦为谗，更以谗释明夷之有言，《易林》本之，遇两兑口、两震言相背或相对者，不谓为谗佞，即谓为争讼。

-----

2017-07-28 23:14:50

《彖》曰：“不利涉大川，入于渊也。”言阳来居坤中而在下，故曰“入渊”。渊者谓坤，不谓坎，入则谓阳入也。

-----

2017-07-28 23:17:25

兑为舌，两舌谓坎上下正反两兑也。以是推讼之有言，亦以坎上下两兑口相背；以其居初，阴微势弱，故曰“小有言”也。

-----

2017-07-28 23:20:05

先天坤居北，后天坎居北，水地合居，故曰“比”。比者，亲也，近也，和也，言水地合居一方，相亲近也。覆之则曰师。师，众也，言坎从坤居北，故势众也。皆合先后天象而立名。

-----

2017-07-28 23:29:09

小畜之反目，亦以两半离相对为反目。而震、巽者，离之上下也。震夫巽妻，故曰“夫妻反目”。

-----

2017-07-29 23:42:24

《易》既取象艮尾，而曰虎尾，则虎亦取象于艮也明矣。况谦三至五震，震为履，震上艮下，故曰“履虎尾”。若以坤为虎，则于象不合矣。

-----

2017-07-29 23:44:51

而既、未济实无艮、兑、震、巽四象，皆用半象也。以茲悟《履·六三》“眇能视，跛能履”，亦以二、三为半离、半震，故《象》曰“不足”。不足者，言离、震未全见也。

-----

2017-07-30 12:05:06

坤为河，二升五，正当坤水之中，故用以涉河，正所谓得尚于中行也

-----

2017-07-30 12:11:44

包巟为大川，亦指坤象。不遐遗者，言二五相距虽遐远，然二必升五，不以远而不升也。朋亡者，阴以阳为朋；亡者，往也，逃也。

-----

2017-07-30 12:12:25

言阳往居五，而为阴朋；五中位，即尚于中行也。

-----

2017-07-30 12:23:46

不戒以孚者，言四及五上皆有应与，不必戒备，自然孚于下也。孚于下，则二五相升降，无不当位也。自汉以来，因小畜有富以其邻之语，于是以不富以其邻五字连读，致《易》义晦涩不明。岂知以其邻意与下属也。

-----

2017-07-30 12:27:30

焦、京皆以复之“朋来无咎”为“崩来无咎”，因复震为反艮也，艮覆则山崩。

-----

2017-07-30 12:29:02

艮为城，艮倒则城覆矣。隍者，城下池。中爻兑泽象也。城覆，则城头正在泽中也。

-----

2017-07-30 12:33:46

阳遇阳，阴遇阴则窒；阳遇阴，阴遇阳则通，是《易林》之定例也。由是推之，《易》凡言“利有攸往”者，皆阳遇阴也，如《大畜·九三》是也；凡言“征凶”者，阳遇阳也，如《大壮·初九》是也。惟阴亦然，革六二前遇三阳，故曰“征吉”，曰“行有嘉”；《小畜·六四》上承二阳，则曰“有孚”，阴遇阳则通也。《颐·六二》曰“征凶”，《六五》“不可涉”，阴遇阴则阻也。

-----

2017-07-30 22:40:39

惟《易》之道，扶阳不扶阴。凡遇阴通之处，不尽谓吉，且恐其过盛以危阳。

-----

2017-07-30 22:56:02

。二阴为三阴所阻，故失四；三阴为二阴所隔，故失初。下震亦艮，上艮亦震，体同也，不分也。卦象来往反复，卦辞亦来往反复。

-----

2017-08-02 22:05:17

噬嗑三爻之昔肉，四爻之乾胏，五爻之乾肉，皆坎象也。

-----

2017-08-02 22:09:24

至于贯象，剥下有三坤，三鱼排叙而进，贯象自著。

-----

2017-08-02 22:12:42

焦氏亦读朋为崩，与京氏同也。汉人无读崩者，独焦读与京同，授受分明矣。

-----

2017-08-02 22:16:49

疾者，嫉也，患也，害也。坤为害，见于《系辞》，见于《孟氏逸象》。出入无疾者，言此一阳，入坤出震，得阴为朋友，阴阳之为朋友，自东汉以来无知者，皆以阴遇阴、阳遇阳为朋。近杭辛斋始谓阴以阳为朋，阳以阴为友，与《易林》暗合。

-----

2017-08-03 12:26:19

出震成乾则复；入巽成坤则姤。复则冬至，姤则夏至也。

-----

2017-08-03 12:27:17

复七日而反姤，姤七日而反复。复而姤，姤而复，循环不已。京房曰：“复者，六爻反复之称也。”复，一日临，二日泰，三日大壮，四日夬，五日乾，六日、七日则反姤；姤，一日遁，二日否，三日观，四日剥，五日坤，六日、七日则反复。共十四日，故复七日不能来复。故出入反复，皆兼复、姤言也。

-----

2017-08-03 12:29:35

余说《易》，向无汉、宋之分，然最咎辅嗣扫象，以从此人不知《易》为何物，避难就易，祛实蹈虚，至程伊川遂出其大无畏之精神，哆口谈空，皆辅嗣作之俑。然辅嗣扫象，辅嗣尚知象，故其注往往由象而生，能与《易林》合，故取之。

-----

2017-08-05 12:10:54

《史记·春申君传》作无望，言无所期望也。京房则以为大旱之卦，万物皆死，无所复望。《汉书·谷永传》，“处无妄之卦运”；《后汉书·崔骃传》，“值无妄之世”，亦皆义取无望。后马、郑皆从之。

-----

2017-08-05 12:14:44

物与无妄者，物咸失其所望。《京房易传》以为大旱之卦，百谷草木咸就枯槁，万物皆死，无所复望。京氏之解，无一字不从象生。艮为火，大离为火，震为百谷草木，而离为枯槁。无云而雷，继以巽风，故万物咸死。

-----

2017-08-05 12:17:48

乃至东汉，《易》象失传，虞翻等既不知艮火象，又不识大离象，诧大旱之说之无根，谓京氏及俗儒失之远矣。

-----

2017-08-07 22:40:53

震为言语，人知之；震为口舌，能饮食，或疑之。乃《易林·井之师》云：“长舌作凶。”是震亦为舌，与兑同，特形较长耳。

-----

2017-08-07 22:43:25

盖饮食者，人之所争，两口相对，争象尤著。争则怒，怒则斗；能节则争端息矣，故节饮食。

-----

2017-08-07 22:44:32

损象云：“君子以惩忿窒欲。”惩忿即慎言语，窒欲即节饮食。损二至上亦颐也，可互为注脚也。

-----

2017-08-07 22:48:39

《颐·初九》之“舍尔灵龟”，艮为龟，初九艮覆，故曰“舍尔灵龟”。与《巽·上九》之“丧斧”，《革·九四》之“改命”义同也，皆用覆也。

-----

2017-08-07 22:51:58

凡《易林》言枯者，无不属离。

-----

2017-08-07 22:53:56

离中虚故枯。乾为实、为金玉，虽老不枯也。

