#+HUGO_BASE_DIR: ~/blog
#+HUGO_SECTION: tech
#+TITLE: Dm200中文系统研究
#+DATE:<2020-06-06 Sat>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS:Linux 系统 emacs cli 技术
#+HUGO_CATEGORIES:技术
#+HUGO_DRAFT: false
#+OPTIONS: \n:t ^:nil _:nil f:nil toc:t num:nil H:5

* 前言
** Dm200 简介
Pomera dm200 是日本人出的一个纯文字处理功能的小机子，特点是键盘手感好，无线功能齐全，虽然原系统显示是黑白但实际是彩色的屏幕，还有纯日文的操作系统，是的，原系统连英文界面都不存在。好在有个日本大牛捣腾出了可以用的 debian 系统，而且是全功能的，这意味着虽然先天不足，但是通过后天的捣腾，中文是可以被支持的。尽管是曲线救国，好歹是能用的。
*** 特点和问题：
- sd卡：官网说是支持到32g的卡，我装系统用的也是32g的卡，不支持uhs，实测好像是这样。卡是大卡，也可以用卡套装小卡，如果没有接触不良的话差别好像不大，不过为了降低风险我用的还是大卡。
- 键盘：虽然是日文格局，但是适应起来门槛不高，只要手感好，什么都不是问题，而且 linux 可以随便捣腾键盘映射。比一般键盘多了几个功能键，正好用在tmux和emacs的映射上。
- 电池：这个机子用的是 arm 的 cpu，还算是比较省电，linux 系统下面 10 个小时应该没什么问题。充电速度也还可以，不过休眠的时候充不进去电好像，还有在用原系统的时候充电，没法关机，得拔了充电线才能关机进入linux系统，可能和原系统的电源管理方案有关。
- 无线功能：现阶段 wifi 和蓝牙支持应该都没什么大问题，但是据说如果同时开启的话会互相干扰，我没有试过蓝牙功能，具体情况不清楚，但是 wifi 用起来是没问题的。
- usb 问题：usb 接口除了用来充电之外，原装系统下好像可以插电脑传数据。除此之外，在 linux 下面其实是可以支持 otg 外接键盘鼠标的，但是有个问题，机子的 usb 接口是不带供电功能的，所以想带动外部设备得用那种带外部供电功能的 hub 才行。实测接鼠标是没问题的。
- 休眠问题：现阶段的休眠功能并不完美，只能说是可用。只支持休眠到内存，没法挂起到硬盘，据说会导致 sd 卡分区 mount 不上的问题，我没试过。原系统有个warp功能，可以快速启动，有人想利用这个改造休眠功能，不过好像失败了。
* 基础系统
** 安装 debian 系统
参考资料：
一堆日文网站，全靠google－translate。
- [[http://hitoriblog.com/?p=51448#DM200][KING JIM ポメラDM200でEmacs、Vim、Ruby、Pythonが動くなんて素敵すぎる！]] :: 这个网站是主要参考对象，内容很详细。
- [[https://www.ekesete.net/log/?p=8940][Linux on Pomera DM200 人柱版 その2]] :: 这个大神是做出这个系统的牛人，一切的源头。
[[https://qiita.com/search?page=2&q=dm200&sort=][Qiita上面的一堆相关资料]]
不算特别多，但是好歹是日本人做的产品，研究也是日本人做得多一些。
- [[https://qiita.com/alt-core/items/d62c6447c607fbf6e8bf][pomera DM200 の Linux 化のメモ]] ::
- [[https://qiita.com/maruime_no_alice/items/07633305fcaaa1f2a6fb][DM200 Linux の高速化を試みるメモ]] :: 这个涉及到加速系统速度的设置，里面有一个驱动挺有用的。
- [[https://qiita.com/alt-core/items/6b16f12ed196bcba1b58][キーボードしかないpomera DM200でも快適X Window環境]] :: 这里有很多基于X的设置，包括如何不用鼠标也能操控X，Keynav这个软件挺有意思。
** 补充
*** 按键自定义
dm200是日文按键布局，相比一般的键盘而言多了几个按键，我把他们重新映射了一下，以方便emacs里面使用。
#+INCLUDE: "/usr/local/share/keymaps/dm200_console.map" 
说明：
- 全角/半角汉字　我把它设置成F11键，然后和Capslock对调了，这个键比较远，对于中文而言，大写锁定很少会用到，反倒是Capslock占了个好位置。
- Menu按键，原系统里面的菜单键，我定义成了PageUp键，上翻页挺方便。
- 一个纯日文的按键，在右边ctrl旁边，改成PageDown键，刚好和Menu键组成一对，好记也好用。
- 无变换键，改成Home键，对于光标快速移动很方便。
- 前候补变换键，改成End键，又刚好组成一对。
* 中文系统
** 需满足几点要求
*** 中文显示
- fbterm :: 现阶段最成熟的方案
- kmscon :: 尝试了编译，没成功
- mlterm :: 据说有个控制台版本，mlterm-fb，支持CJK，但是由于fbterm有yong输入法，所以没试，用这个就只能用emacs里面的输入法了。
*** 中文输入法
两种方案 
**** fbterm相结合的输入法
- uim-fep：虽然能打中文，但是仅仅只是能用，用起来体验极差，日本人弄的系统默认用这个，偶尔在终端打字可能用得上，我不用，我尝试过自己转换码表，但是这东西好像对码表的大小有限制，码表一大起来，就崩给你看。
- yong输入法：优点是速度快，缺点是可定制性差，配置文件影响的是X下面的输入法，fbterm下面的yong输入法并没有全部读取配置文件，颜色什么的只能通过源码修改。还有在终端下和vim搭配有点不大稳定，现在怀疑是tf卡套接触不良的原因，因为换了大卡之后问题少了很多。yong输入法和emacs搭配好像还挺好的，暂时没发现太大的问题。
**** 编辑器内嵌的输入法
***** vim插件vimim :: 
 速度太慢放弃。真的是慢，没法用。
***** emacs插件 ::
pyim：现阶段采用的方案，缺点是启动emacs之后第一次切换略慢，之后就顺畅了。还有如果想要流畅，最好选择用minibuffer的方式，但是容易被其他信息覆盖。
emacs－rime：据说速度快，但是得重新编译emacs，还有一堆东西得重新折腾，尝试过，编译全部很顺利，一运行就崩溃，暂时不清楚问题出在哪里。
*** 文本编辑器
两大神器：
**** Vim
速度快，编辑功能强大，但是之前有一段时间我用起来很容易崩溃，怀疑是和输入法配合的问题，现在我只用它来写写配置文件，中文处理基本上交给了emacs。
**** Emacs
有强大的org-mode，配合deft管理笔记不要太好用。org-capture可以随时捕捉灵感，journal写写日记，一个软件就齐全了。缺点是配置相对复杂，不过一次配置，受益无穷，还是值得的。
*** 文本同步与共享
**** 本机模式 
卡里有个fat分区，是专门用来和原系统交换文件用的，可以直接mount，好像也可以在原系统里面直接用usb直接连电脑拷文件，在debian里面不行。
**** 网络模式 
-　emacs支持evernote-mode，分享文本还是很方便的。:: 国内使用可以把主机改成印象笔记，速度快一些。
-　用git同步 :: 这个适合整个文件的同步，git很强大，可以有很多种利用方式，我就存点东西，写个博客。
-　网络粘贴板 :: 可以用ubuntu-pastbin之类的网络粘贴板，也可以用netcat模式的termbin，对于临时复制粘贴文本我采用tibiji.com这种网站，配合w3m还是挺方便的，尤其是emacs里面的w3m，直接编辑，交换文本完全无缝。
** 纯控制台模式（无 X window）
*** 方案 1
*** 方案2

** X Window
