#+TITLE: 汉书百官公卿表
#+OPTIONS: ^:nil num:nil H:1
#+TAGS: 历史(h) 古籍(o) 汉书

* 三公
** 相国、丞相（大司徒）
秦官​金印紫绶，掌丞天子助理万机。​有两长史，秩千石​秦有左右，高帝即位，置一丞相，十一年更名相国，绿绶。孝惠、高后置左右丞相，文帝二年复置一丞相。​哀帝元寿二年更名大司徒。
** 太尉（大司马、将军）
秦官​金印紫授，掌武事。​有长史，秩千石。​武帝建元二年省。元狩四年初置大司马，以冠将军之号，宣帝地节三年置大司马，不冠将军，亦元印绶官属。成帝绥和元年初赐在司马金印紫绶，置官属，禄比丞相，去将军。哀帝建平二年复去大司马印绶、官属，冠将军如故。元寿二年复赐大司马印绶，置官属，去将军，位在司徒上。
** 御史大夫（大司空、御史中丞）
秦官​位上卿，银印青绶，掌副丞相。一曰中丞，在殿中兰台，掌图籍秘书，外督部刺史，内领侍御史员十五人，受公卿奏事，举劾按章。​有两丞，秩千石。​成帝绶和元年更名大司空，金印紫绶，禄比丞相，置长史如中丞，官职如故。哀帝建平二年复为御史大夫，元寿二年复为大司空，御史中丞更名御史长史。
** 太傅、太师、太保（古官三公）
古官​金印紫绶。​太傅，高后元年初置。后省，八年复置。哀帝元寿二年复置。位在三公上。太师、太保，平帝元始元年皆初置。太师位在太傅上，太保次太傅。
* 九卿
** 奉常（太常、秩宗）
秦官​掌宗庙礼仪，有丞。​景帝中六年更名太常。王莽改太常曰秩宗。
*** 六令丞
**** 太乐
掌伎乐
**** 太祝
掌祭祀​景帝中六年更名太祝为祠祀，武帝太初元年更曰庙祀，初置太卜。
**** 太宰
掌膳食
**** 太史
掌天时星历
**** 太卜
掌占卜
**** 太医
掌医药
*** 两长丞
**** 都水
总掌治水
**** 均官
掌均输
*** 诸庙寝园食官令长丞
*** 雍五畤相关
**** 雍太宰
**** 雍太祝
**** 五畤尉
*** 博士
秦官​博古通今，备顾问，传授儒学。​​秩比六百石，员多至数十人。武帝建元五年初置《五经》博士，宣帝黄龙元年稍增员十二人。
*** 诸陵县
掌陵寝诸事​元帝永光元年分诸陵邑属三辅。
** 郎中令（光禄勋）
秦官​掌宫殿掖门户，有丞。​武帝太初元年更名光禄勋。
*** 大夫
掌论议，有太中大夫、中大夫、谏大夫，皆无员，多至数十人。
**** 太中大夫
太中大夫秩比千石
**** 中大夫
太初元年更名中大夫为光禄大夫，秩比二千石
**** 谏大夫
武帝元狩五年初置谏大夫，秩比八百石
*** 郎
掌守门户，出充车骑，有议郎、中郎、侍郎、郎中，皆无员，多至千人。
**** 议郎
秩比六百石
**** 中郎
秩比六百石
***** 五官、左、右三将
秩皆比二千石
**** 侍郎
秩比四百石
**** 郎中
秩比三百石
***** 车、户、骑三将
秩皆比千石
*** 谒者
掌宾讚受事​员七十人，秩比六百石
**** 谒者仆射
秩比千石
*** 期门（虎贲郎）
掌执兵送从。​比郎，无员，多至千人。武帝建元三年初置，平帝元始元年更名虎贲郎。
**** 期门仆射
秩比千石
**** 虎贲中郎将
秩比二千石
*** 羽林
掌送从，次期门。​羽林有令丞。​武帝太初元年初置，名曰建章营骑，后更名羽林骑。又取从军死事之子孙养羽林，官教以五兵，号曰羽林孤儿。宣帝令中郎将、骑都尉监羽林，秩比二千石。
** 卫尉（中大夫令）
秦官​掌宫门卫屯兵，有丞。​景帝初更名中大夫令，后元年复为卫尉。
*** 公车司马
*** 卫士
*** 旅贲
*** 诸屯卫候
*** 司马二十二官
*** 长乐卫尉
*** 建章卫尉
*** 甘泉卫尉
** 太仆
秦官​掌舆马，有两丞。​​秩中二千石。
*** 太厩
五丞一尉
*** 未央
五丞一尉​未央厩令
*** 家马（挏马）
五丞一尉​主供天子私用，非大祀戎事军国所需，故谓之家马也。​武帝太初元年更名家马为挏马，初置路。
四令丞
**** 车府
**** 路
厩名​，在未央宫。
**** 骑马
厩名​，在长安城外。
**** 骏马
*** 五监长丞
龙马、闲驹、橐泉、騊駼、承华龙马，大宛厩也。闲驹，养马之所​。橐泉，厩名，在橐泉宫下。騊駼，厩名，在长安城外。承华，厩名。
*** 边郡六牧师苑令
陇西、天水、安定、北地、上郡、西河六郡
*** 牧橐令丞
牧养骆驼
*** 昆蹄令丞
良马厩
*** 中太仆
掌皇太后舆马，不常置也。
** 廷尉（大理、作士）
秦官​掌刑辟。​​秩中二千石。​有正、左右监，秩皆千石。​景帝中六年更名大理，武帝建元四年复为廷尉。宣帝地节三年初置左右平，秩皆六百石。帝元寿二年复为大理。王莽改曰作士。
** 典客（大行令、大鸿胪、典乐）
秦官​掌诸归义蛮夷，有丞。​​秩中二千石。​景帝中六年更名大行令，武帝太初元年更名大鸿胪。王莽改大鸿胪曰典乐。
*** 行人
武帝太初元年更名行人为大行令
*** 译官
*** 别火
狱令，主治改火之事。​武帝太初元年，初置别火。
*** 郡邸长丞
诸郡在京师之邸，郡国朝宿之舍。​初，置郡国邸属少府，中属中尉，后属大鸿胪。
** 宗正
秦官​掌亲属，有丞。​​秩中二千石。​平帝元始四年更名宗伯。​王莽并其官于秩宗。
*** 都司空令丞
都造砖瓦，用以修葺宫殿及各城门楼
*** 内官长丞
初，内官属少府，中属主爵，后属宗正。
*** 公主家令
*** 公主门尉
** 治粟内史（大农令、大司农）
秦官。​掌谷货，有两丞。​​秩中二千石。​景帝后元年更名大农令，武帝太初元年更名大司农。王莽改大司农曰羲和，后更为纳言。
*** 五令丞
**** 太仓
京城储粮大仓
**** 均输
统一征收，买卖和运输货物，以调剂各地需求，郡国设均输官。
**** 平准
官府转输物资，平抑物价，由平准令掌管。
**** 都内
主管贡献方物及货币
**** 籍田
初为帝王亲耕，并设仓，后因仓设官。
*** 两长丞
**** 干官
掌铸钱事。​初，斡官属少府，中属主爵，后属大司农。
**** 铁市
*** 郡国诸仓
*** 农监
*** 都水六十五官长丞
*** 搜粟都尉
武帝军官，不常置。
** 少府
秦官​掌山海池泽之税，以给供养，有六丞。​​秩中二千石。​王莽改少府曰共工。
*** 十六官令丞
**** 尚书
初掌殿内文书，后掌群臣章奏。
**** 符节
掌符节之事。
**** 太医
主治宫廷人员之病。
**** 太官
掌膳食，兼掌四时进献果实。​太官七丞。
**** 汤官
供饼饵果实。
**** 导官
掌御用粮食。
**** 乐府
主管宫廷、巡行、祭祀之音乐，兼采民歌及配曲。​乐府三丞。​绥和二年，哀帝省乐府。
**** 若庐
主治库兵及诏狱。
**** 考工室
主作兵器弓弩及织绶诸杂工。​武帝太初元年更名考工室为考工。
**** 左弋
掌助弋射之事，兼造兵器。​武帝太初元年更名左弋为飞（次蜚）。​飞掌弋射，有九丞两尉。
**** 居室
拘禁犯人之所。​武帝太初元年更名居室为保宫
**** 甘泉居室
武帝太初元年更名为昆台。​昆台五丞。
**** 左右司空
主造陶瓦，兼石刻工艺。
**** 东织
**** 西织
掌皇家丝帛织造，在未央宫。​河平元年省东织，更名西织为织室。
**** 东园匠
掌陵墓内器物制作和供应。
*** 三长丞
**** 庖人
掌宰割者。
**** 都水
掌陂泽。
**** 均官
掌少府均输事。
*** 上林中十池监
*** 八官食丞
**** 中书谒者令
掌机要，由宦者充任。​成帝建始四年更名中书谒者令为中谒者令，初置尚书，员五人，有四丞。
**** 黄门令
主省中诸宦者
**** 鉤盾令
宦者典诸近池苑囿游观之处。​钩盾五丞两尉
**** 尚方令
掌管供应制造帝王所用器物。
**** 御府令
宦者典宫婢作中衣服及补浣之属。
**** 永巷令
宦者典宫婢侍使。​武帝太初元年更名永巷为掖庭。​掖廷八丞。
**** 内者令
掌客庭布张诸衣物。
**** 宦者令
管内廷宦者。​宦者七丞。
*** 仆射
首长之义。秦汉时凡侍中、尚书、博士、谒者、郎等官，都有仆射。
*** 署长
*** 中黄门
宦者掌给事中
* 中尉（执金吾）

秦官​掌徼循京师。​秩中二千石。​有两丞、候、司马、千人。​武帝太初元年更名执金吾。
** 四令丞
*** 中垒
​两尉
*** 寺互
初，寺互属少府，中属主爵，后属中尉。
*** 武库
三丞
*** 都船
主船之官。​三丞
** 式道左右中侯
凡左、右、中三侯车驾出，掌在前清道。车驾还，持麾至宫门，门乃开。
** 侯丞
** 左右京辅都尉
** 尉丞兵卒
* 太子太傅、少傅
古官。
** 太子门大夫
** 率更令
主庶子舍人更值。
** 家令
主仓狱。
** 家府
比二千石。
** 仆
主马。
** 庶子
秩四百石，如中郎，无员。
** 先马
前驱也。
** 舍人
* 将作少府（将作大匠）
秦官​掌治宫室。​有两丞、左右中候。​景帝中六年更名将作大匠。
** 七令丞
*** 石库
*** 东园主章
掌大材，以供东园大匠。​武帝太初元年更名东园主章为木工。
*** 左右前后中校
成帝阳朔三年省中候及左右前后中校五丞。
** 主章长丞
* 詹事
秦官。​掌皇后、太子家，有丞。​成帝鸿嘉三年省詹事官，并属大长秋。
** 太子率更
掌知漏刻，秩千石。
** 家令
主仓狱，秩千石。
** 仆
** 中盾
** 卫率
** 厨厩长丞
** 诸宦官
皇后属官，统称为中官。
** 长信詹事
掌皇太后宫。以太后所居宫为名。​景帝中六年更名长信少府，平帝元始四年更名长乐少府。
* 将行（大长秋）
秦官。​景帝中六年更名大长秋，或用中人，或用士人。
* 典属国
秦官。​掌蛮夷降者。​武帝元狩三年昆邪王降，复增属国，置都尉、丞、侯、千人。
** 九译令
掌翻译。​成帝河平元年省并大鸿胪。
* 水衡都尉
掌上林苑，有五丞。​武帝元鼎二年初置。​王莽改水衡都尉曰予虞。
** 九官令丞
*** 上林
​初属少府。
*** 均输
掌上林苑中均输之事。
*** 御羞
掌帝王膳馐原料。​初属少府。
*** 禁圃
掌禁苑种植事宜。
*** 楫櫂
掌船之官。
*** 钟官
主铸钱之官。
*** 技巧
主刻范。​成帝建始二年省
*** 六厩
成帝建始二年省
*** 辩铜
主原料。
** 衡官
主平其税人。​​初属少府。
** 水司空
** 都水农仓
掌上林苑中农仓。
** 甘泉上林都水七官丞
上林有八丞十二尉，均输四丞，御羞两丞，都水三丞，禁圃两尉，甘泉上林四丞。
* 三辅
元鼎四年更置三辅都尉、都尉丞各一人。
** 内史
周官，秦因之。​掌治京师。​景帝二年分置左右内史。
*** 左内史（左冯翊）
**** 廪栖令丞尉
掌祭祀牺牲之属。
**** 左都水
**** 铁官
**** 云垒
**** 长安四市四长丞
*** 右内史（京兆尹）
右内史武帝太初元年更名京兆尹。
**** 两令丞
***** 长安令丞
***** 厨令丞
掌帝王巡幸境内离宫别馆时之供帐。
**** 两长丞
***** 都水
***** 铁官
** 主爵中尉（都尉、右扶风）
秦官。​掌列侯。​景帝中六年更名都尉，武帝太初元年更名右扶风。治内史右地。列侯更属大鸿胪。
*** 掌畜令丞
*** 四长丞
**** 右都水
**** 铁官
**** 厩
**** 雍厨
* 武职
** 前后左右将军
周末官，秦因之。​金印紫绶。皆掌兵及四夷。​有长史，秩千石。​皆周末官，秦因之，位上卿。汉不常置。或有前后，或有左右。
** 护军都尉（司寇）
秦官。​武帝元狩四年属大司马，成帝绥和元年居大司马府比司直，哀帝元寿元年更名司寇，平帝元始元年更名护军。
** 司隶校尉
周官。​武帝征和四年初置。持节，从中都官徒千二百人，捕巫蛊，督大奸猾。后罢其兵，察三辅、三河、弘农。元帝初元四年去节，成帝元延四年省。绥和二年，哀帝复置，但为司隶，属大司空，比司直。
** 城门校尉
掌京师城门屯兵。​有司马、十二城门候。
** 八校尉
武帝初置，有丞、司马。
*** 中垒校尉
掌北军垒门内，外掌西域。
*** 屯骑校尉
掌骑士。
*** 步兵校尉
掌上林苑门屯兵。
*** 越骑校尉越骑。
*** 长水校尉
掌长水宣曲胡骑。
*** 胡骑校尉
掌池阳胡骑，不常置。
*** 射声校尉
掌待诏射声士。
*** 虎贲校尉
掌轻车。​
** 西域都护加官
宣帝地节二年初置，以骑都尉、谏大夫使护西域三十六国，有副校尉，秩比二千石，丞一人，司马、侯、千人各二人。
** 戊已校尉
掌西域屯田事务。​元帝初元元年置，有丞、司马各一人，侯五人，秩比六百石。
** 奉车都尉
掌御乘舆车。​武帝初置，秩比二千石。
** 驸马都尉
掌驸马。​武帝初置，秩比二千石。
* 中朝官（内朝官）
** 侍中
得入禁中。
** 左右曹诸吏
诸曹受尚书事，诸吏得举法。
** 散骑
散骑骑马，并乘舆车，献可替否。
** 中常侍
得入禁中。
** 给事中
掌顾问应对，位次中常侍。
* 监御史（刺史、牧）
秦官。​掌监郡。​汉省，丞相遣史刺州，不常置。​武帝元封年初置部刺史，掌奉诏条察州，秩六百石，员十三人。​成帝绥和元年更名牧，秩二千石。哀帝建平二年复为刺史，元寿二年复为牧。
* 郡县
** 郡
*** 郡守（太守）
秦官。​掌治其郡，秩二千石。​有丞，边郡又有长史，掌兵马，秩皆六百石。​景帝中二年更名太守。
*** 郡尉（都尉）
秦官。​掌佐守典武职甲卒。​秩比二千石。有丞，秩皆六百石。​景帝中二年更名都尉。
** 边郡
*** 关都尉
秦官。设于扼要之所。​
**** 关长
**** 关尉
**** 关丞
*** 农都尉
主屯田植谷。
*** 属国都尉
安置降附者，掌管属国事务。
** 县
*** 县令、县长
皆秦官。​掌治其县。​万户以上为令，秩千石至六百石。减万户为长，秩五百石至三百石。
**** 长吏
***** 县丞
秩四百石至二百石。
***** 县尉
秩四百石至二百石。
**** 少吏
***** 斗食
百石以下
***** 佐史
*** 亭长
**** 乡
***** 三老
三老掌教化。
***** 有秩
***** 啬夫
啬夫职听论，收赋税。兼为吏民移请过所。手续是由乡到县，经县丞批发。与有秩类似。
***** 游徼
游徼徼循禁贼盗。
** 国、邑、道
列侯所食县曰国，皇太后、皇后、公主所食曰邑，有蛮夷曰道。
